[package]
name = "metallic"
version = "0.1.0"
authors = ["feminstincts <feminstincts@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.6.0"

[package.metadata.bootimage]
default-target = "x86_64-metallic.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"