[package]
name = "metallic"
version = "0.1.0"
authors = ["feminstincts <feminstincts@gmail.com>"]
edition = "2018"

[dependencies]
# the profile used for `cargo build`
bootloader = "0.5.1"

[package.metadata.bootimage]
default-target = "x86_64-metallic.json"